@startuml 演習３－４
object "車体:車" as car{
    
}
object "タイヤ１:タイヤ" as tire1{
    
}
object "タイヤ２:タイヤ" as tire2{
    
}
object "タイヤ３:タイヤ" as tire3{
    
}
object "タイヤ４:タイヤ" as tire4{
    
}
car-up-tire1
car-down-tire2
car-ri-tire3
car-le-tire4

@enduml