@startuml 演習６－３
[*] --> メニュー
state c <<choice>>
メニュー --> 予約と確認
メニュー --> 今の順番

予約と確認 --> c
c --> あなたの順番 :登録ボタン
c --> あなたの順番 :確認ボタン
c --> メニュー :削除ボタン

今の順番 --> メニュー :メニューへ
あなたの順番 --> メニュー :メニューへ

メニュー -right-> [*]
@enduml